### ISSUE TITLE
Editing & viewing translations still not quite right

### ISSUE THREAD

**Issue by spikedee** [kaleissin/CALS#31]
It appears the translations system has acquired a few kinks since my last adventure in bug reporting.

When you click on a translation, like so:
![testarosa-clicky](https://cloud.githubusercontent.com/assets/10866161/6060816/e63f9636-ad06-11e4-9305-a79ce2a135ce.png)

You *not* gonna get it all, yo, 'cause this error appears:

![testarosa-fail](https://cloud.githubusercontent.com/assets/10866161/6060815/e5a83b24-ad06-11e4-80a7-bca28605cc10.png)

The username of the translator appears in the URL (highlighted), e.g. if someone were to click on one of my translations, "admin" in the URL above would be "spikedee." I suspect that this has *something* to do with the issue. (**Edit:** It works correctly *if* you remove the username from the URL, which seems to corroborate my suspicions. No idea why I didn't think to actually try that to start with, given said suspicions.) 

I originally got this hunch because when you click on a link to one of your own translations, it appears to work correctly, taking you to the page to edit the translation. But when you actually try to submit an edit, you get an error message exactly like the first one (I guess it doesn't want me to touch it there...):

![no-edits-4-u](https://cloud.githubusercontent.com/assets/10866161/6060985/0d51d264-ad09-11e4-89c0-737ebed21418.png)

 (**Edit 2:** Even though it throws this error again, the edit *does* go through successfully. Guess it has mixed feelings about touching it there...) 

(Oh yeah, the conlang in the screenshot above is in all likelihood a *much* bigger mess than this at the moment. It's one I'm working on for a friend's world-building project, and it's been undergoing a major overhaul and lots of tinkering recently to better suit her tastes, but I seriously digress.)

Also, I didn't know about the CALS github until the admin showed me when I went bug-reporting before; thanks for that! I hope this bug report is a bit more helpful than the last. A link on the main site to the CALS' issues page on github would be helpful too, hinthint nudgenudge. Or maybe I just overlooked it.

**Comment by kaleissin** [comment]
Thanks for the most excellent bug report! With screenshots even!

I have a pretty good idea what causes these 404s, the pages use outdated code to build the url.

**Comment by kaleissin** [comment]
Whoa, with urls even, this'll be a walk in the park!

**Comment by kaleissin** [comment]
See if it all works out as expected at the dev-site: http://dev.cals.nu/translation/ What you do there will  be reflected in the main site, the difference is all things debugging are turned on.

**Comment by spikedee** [comment]
Yep, everything seems to be working fine. :D

**Comment by kaleissin** [comment]
Good testers don't grow on trees! They also save a lot of time, prevent heart burn, and aren't paid enough =)

The fixes are in production, the source have been pushed, closing this issue.
